apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healingpolicies.demo.kcd2025   # plural CRD name
spec:
  group: demo.kcd2025                  # grupo API personalizado
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                pipelineName:
                  type: string
                pipelineNamespace:
                  type: string
                deploymentName:
                  type: string
                deploymentNamespace:
                  type: string
                latencyThresholdSeconds:
                  type: number
                errorRateThreshold:
                  type: number
            status:
              type: object
              properties:
                lastAction:
                  type: string
                message:
                  type: string
  scope: Namespaced
  names:
    kind: HealingPolicy
    plural: healingpolicies
    singular: healingpolicy
    shortNames: [ "hp" ]