apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healingpolicies.demo.kcd
spec:
  group: demo.kcd
  names:
    kind: HealingPolicy
    listKind: HealingPolicyList
    plural: healingpolicies
    singular: healingpolicy
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                maxLatencySeconds:
                  type: number
                maxErrorRate:
                  type: number
                action:
                  type: string
