apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: image-name
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"

    - name: run-tests
      runAfter: ["fetch-source"]
      taskSpec:
        workspaces:
          - name: shared-workspace
        steps:
          - name: test
            image: golang:1.20
            workingDir: /workspace/shared-workspace
            script: |
              #!/bin/sh
              go mod tidy
              go test ./... -v

    - name: build-image
      runAfter: ["run-tests"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)

    - name: deploy
      runAfter: ["build-image"]
      taskSpec:
        steps:
          - name: rollout
            image: bitnami/kubectl:latest
            script: |
              #!/bin/sh
              kubectl rollout restart deployment/demo-microservice
