apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline-run
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: demo-pipeline
  serviceAccountName: tekton-pipelines
  params:
    - name: git-url
      value: https://github.com/samircastro27/ci-cd-autocurable.git
    - name: git-revision
      value: main
    - name: image-name
      value: cuembybot/demo-microservice:latest
    - name: DOCKERFILE
      value: ./microservice/Dockerfile
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
