apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tb-github                        # Binding para eventos de GitHub
  namespace: tekton-pipelines
spec:
  params:
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)  # Extrae la URL del repo del payload JSON
  - name: gitrevision
    value: $(body.after)                 # Extrae el SHA del commit (en eventos "push")
  - name: gitref
    value: $(body.ref)                   # Extrae la referencia (ej: "refs/heads/main")
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tt-github
  namespace: tekton-pipelines
spec:
  params:
  - name: gitrepositoryurl
  - name: gitrevision
  - name: gitref
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: demo-pipeline-run-   # Tekton generará un nombre único para la PipelineRun
      namespace: tekton-pipelines
    spec:
      serviceAccountName: tekton-pipelines   # ServiceAccount con permisos de ejecutar pipeline (y despliegue)
      pipelineRef:
        name: demo-pipeline             # Referencia a la pipeline definida anteriormente
      params:
      - name: git-url
        value: $(tt.params.gitrepositoryurl)
      - name: git-revision
        value: $(tt.params.gitrevision)
      - name: image-name
        value: "cuembybot/demo-microservice:latest"
      - name: DOCKERFILE
        value: ./microservice/Dockerfile
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi           # Se crea un PVC dinámico para compartir datos entre Tasks
      - name: dockerconfig
        emptyDir: {}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: el-github
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa    # SA que ejecutará el EventListener Pod
  triggers:
  - name: github-trigger
    interceptors:
      - ref:
          name: "cel"
        params:
          - name: "filter"
            value: "header.match('X-GitHub-Event', 'push')"
    bindings:
      - ref: tb-github
    template:
      ref: tt-github