apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-microservice-sm
  labels:
    release: prometheus                # etiqueta usada por el Prometheus operator para asociar monitors
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-microservice           # selecciona el Service del microservicio
  endpoints:
  - port: http                         # nombre del puerto que definimos en el Service (8080)
    path: /metrics                     # ruta de métricas
    interval: 15s                      # scrape cada 15 segundos (ajustable)
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tekton-pipelines-sm
  labels:
    release: prometheus
  namespace: tekton-pipelines
spec:
  selector:
    matchLabels:
      app: tekton-pipelines-controller # etiqueta del Service de Tekton controller
  namespaceSelector:
    matchNames: 
      - tekton-pipelines               # buscamos en el ns de Tekton
  endpoints:
  - port: http-metrics                 # el puerto 9090 del Service Tekton controller se llama "http-metrics"
    path: /metrics
    interval: 30s