apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice
  namespace: demokcd2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-microservice
  template:
    metadata:
      labels:
        app: demo-microservice
    spec:
      containers:
      - name: app
        image: cuembybot/demo-microservice:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
